# Generated by Django 5.1.1 on 2024-10-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('uz', 'Узбекский')], default='ru', max_length=2),
        ),
    ]
