# Generated by Django 5.1.1 on 2024-10-09 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_category_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='quiz.subject'),
        ),
    ]
