# Generated by Django 5.1.1 on 2024-10-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_category_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='BachelorProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('first_subject', models.CharField(max_length=255)),
                ('second_subject', models.CharField(max_length=255)),
            ],
        ),
    ]
