# Generated by Django 5.1.1 on 2024-10-09 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_bachelorprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bachelorprogram',
            name='first_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.subject'),
        ),
        migrations.AlterField(
            model_name='bachelorprogram',
            name='second_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_bachelor', to='quiz.subject'),
        ),
    ]
