# Generated by Django 5.1.1 on 2024-10-11 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_bachelorprogram_first_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bachelorprogram',
            name='required_subject1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_subject_first', to='quiz.subject'),
        ),
        migrations.AddField(
            model_name='bachelorprogram',
            name='required_subject2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_subject_second', to='quiz.subject'),
        ),
        migrations.AddField(
            model_name='bachelorprogram',
            name='required_subject3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_subject_third', to='quiz.subject'),
        ),
    ]
