# Generated by Django 5.1.1 on 2024-10-13 10:30

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_bachelorprogram_required_subject1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
    ]
