# Generated by Django 5.1.1 on 2024-10-13 10:38

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_question_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
