# Generated by Django 5.1.1 on 2024-10-13 10:43

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_question_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
