# Generated by Django 5.1.1 on 2024-10-13 13:24

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_question_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
