# Generated by Django 5.1.1 on 2024-10-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_alter_question_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
        migrations.AddField(
            model_name='bachelorprogram',
            name='first_subject_point',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bachelorprogram',
            name='required_subject1_point',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bachelorprogram',
            name='required_subject2_point',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bachelorprogram',
            name='required_subject3_point',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bachelorprogram',
            name='second_subject_point',
            field=models.FloatField(default=0.0),
        ),
    ]
